### PR TITLE
Consume latest toolkit and fix dangling promise bug

### LINKED ISSUE #810: Action can wait for at least 27 minutes when no progress is being made on the download
Example: https://github.com/ccmbioinfo/osmp/runs/6692774526?check_suite_focus=true

This hung on `Received 1189052508 of 1193246812 (99.6%)` for almost half an hour before we noticed and cancelled the workflow run.

### PR DESCRIPTION
**Pull request by chkimes**
This PR updates to the latest actions/cache version published from the toolkit, which contains https://github.com/actions/toolkit/pull/1484 and should fix #810.

## Description
See https://github.com/actions/toolkit/pull/1484 for details on the Azure blob fixes. The cache action contains an additional fix for dangling promises that prevents the process from ending despite the cache being fully restored.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (add or update README or docs)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/restore.ts [hunk 1]
```diff
@@ -1,10 +1,3 @@
-import restoreImpl from "./restoreImpl";
-import { StateProvider } from "./stateProvider";
+import { restoreRun } from "./restoreImpl";
 
-async function run(): Promise<void> {
-    await restoreImpl(new StateProvider());
-}
-
-run();
```
Comment (chkimes) [inline src/restore.ts:8]: This caused a lot of problems in tests - the file was exporting _and_ executing the run function, which feels like an unusual pattern. I moved this into `restoreImpl` and just reference it here directly, which required a bunch of non-functional test reactions.

**Review by cwille97 — APPROVED** [review]

**Comment by bbrzoska** [comment]
Hey @cwille97, any chance this fix can get released/tagged anytime soon? 🙏
